name: Daily News Digest

on:
  schedule:
    - cron: "25 1 * * *"   # Runs every day at 07:30 UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ALGION_KEY: ${{ secrets.ALGION_KEY }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python main.py
